/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.interfacegraphique;

import com.company.tools.XmlTools;
import java.awt.Color;
import java.io.StringWriter;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.xml.stream.XMLOutputFactory;
import javax.xml.stream.XMLStreamWriter;

/**
 *
 * @author DELL XPS
 */
public class InterfaceAut extends java.awt.Frame {
    private String select = "Jour(s)";
  static String em;
    /**
     * Creates new form InterfaceAut
     */
    public InterfaceAut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        pan = new javax.swing.JPanel();
        mailEmetteur = new javax.swing.JLabel();
        nomEmetteur = new javax.swing.JLabel();
        choixDuree = new javax.swing.JComboBox<>();
        titreFenetreProp = new javax.swing.JLabel();
        nomRecepteur = new javax.swing.JLabel();
        texteDuree = new javax.swing.JTextField();
        texteMailEmetteur = new javax.swing.JTextField();
        duree = new javax.swing.JLabel();
        mailRecepteur = new javax.swing.JLabel();
        texteEmetteur = new javax.swing.JTextField();
        textMailRecepteur = new javax.swing.JTextField();
        texteRecepteur = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mailEmetteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailEmetteur.setText("Mail émetteur :");
        mailEmetteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(mailEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 160, 20));

        nomEmetteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomEmetteur.setText("Nom émetteur : *");
        nomEmetteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(nomEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 20));

        choixDuree.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        choixDuree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jour(s)", "Semaine(s)", "Mois", "Année(s)", "Durée Indéterminée" }));
        choixDuree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixDureeActionPerformed(evt);
            }
        });
        pan.add(choixDuree, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, 20));

        titreFenetreProp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titreFenetreProp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreFenetreProp.setText("Je souhaite avoir l'autorisation de troque : ");
        titreFenetreProp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titreFenetreProp.setPreferredSize(new java.awt.Dimension(240, 40));
        pan.add(titreFenetreProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 50));

        nomRecepteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomRecepteur.setText("Nom récepteur : *");
        nomRecepteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(nomRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 20));

        texteDuree.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pan.add(texteDuree, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 60, 20));

        texteMailEmetteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pan.add(texteMailEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 330, 20));

        duree.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        duree.setText("Durée de validité : *");
        duree.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 160, 20));

        mailRecepteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailRecepteur.setText("Mail récepteur : ");
        mailRecepteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(mailRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 160, -1));

        texteEmetteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pan.add(texteEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 330, 20));

        textMailRecepteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pan.add(textMailRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 330, -1));

        texteRecepteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pan.add(texteRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 330, 20));

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setText("Envoyer la demande d'autorisation");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pan.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 370, 40));

        add(pan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void choixDureeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixDureeActionPerformed
        JComboBox cb = (JComboBox) evt.getSource();

        select = cb.getSelectedItem().toString();

        if(select.compareTo("Durée Indéterminée") == 0){
            texteDuree.setFocusable(false);
            texteDuree.setBackground(new Color(230,230,230));

            pan.repaint();
        }
        else{
            texteDuree.setFocusable(true);
            texteDuree.setBackground(new Color(255,255,255));

            pan.repaint();
        }
    }//GEN-LAST:event_choixDureeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int err = 0;
        
        
        if(texteEmetteur.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Le champs \"Nom émetteur\" doit être rempli!");
            err = 1;
        }
        else {
       em = texteEmetteur.getText();
        
        }
        
        if(texteRecepteur.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Le champs \"Nom récepteur\" doit être rempli!");
            err = 1;
        }
        
        if(select.compareTo("Durée Indéterminée") != 0){
            if(texteDuree.getText().isEmpty()){
                if(select.compareTo("Année(s)") == 0){
                    JOptionPane.showMessageDialog(null,"Vous devez spécifier un nombre d'Année(s)!");
                    err = 1;
                }
                else{
                   JOptionPane.showMessageDialog(null,"Vous devez spécifier un nombre de " + select + "!");
                   err = 1;
                }
            }
            
            if(!texteDuree.getText().matches("[0-9]*")){
                JOptionPane.showMessageDialog(null,"Vous devez entrer un enier pour spécifier la durée!");
            }
        }
        
        if(err != 1){
            XmlTools xmlTools = new XmlTools();
            if(xmlTools.creerAuth(texteEmetteur.getText(), texteRecepteur.getText(), Integer.parseInt(texteDuree.getText()),texteMailEmetteur.getText(), textMailRecepteur.getText()))
                JOptionPane.showMessageDialog(null,"Demande cree avec succes");
            else
                JOptionPane.showMessageDialog(null,"Erreur veuillez resseayer plus tard");
                
        }
    
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceAut().setVisible(true);
            
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> choixDuree;
    private javax.swing.JLabel duree;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel mailEmetteur;
    private javax.swing.JLabel mailRecepteur;
    private javax.swing.JLabel nomEmetteur;
    private javax.swing.JLabel nomRecepteur;
    private javax.swing.JPanel pan;
    private javax.swing.JTextField textMailRecepteur;
    private javax.swing.JTextField texteDuree;
    private javax.swing.JTextField texteEmetteur;
    private javax.swing.JTextField texteMailEmetteur;
    private javax.swing.JTextField texteRecepteur;
    private javax.swing.JLabel titreFenetreProp;
    // End of variables declaration//GEN-END:variables
}
