/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.interfacegraphique;

import com.company.tools.Objet;
import com.company.tools.XMLParser;
import com.company.tools.XmlTools;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author qbiss
 */
public class InterfaceAffichProp extends java.awt.Frame {
    public static List<Objet> lo = new ArrayList<>();
    public static int nbObjet = 0;
    public static InterfaceAffichProp iap;
    public static int sizeYAffich = 350;
    /**
     * Creates new form InterfaceAffichProp
     */
    public InterfaceAffichProp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();
        titreFenetreAffichProp = new javax.swing.JLabel();
        nomEmetteur = new javax.swing.JLabel();
        nomRecepteur = new javax.swing.JLabel();
        duree = new javax.swing.JLabel();
        mailEmetteur = new javax.swing.JLabel();
        mailRecepteur = new javax.swing.JLabel();
        coordonnees = new javax.swing.JLabel();
        laProposition = new javax.swing.JLabel();
        titreProp = new javax.swing.JLabel();
        proposition = new javax.swing.JLabel();
        desire = new javax.swing.JLabel();
        boutonFaireConProp = new javax.swing.JButton();
        boutonAccepter = new javax.swing.JButton();
        boutonRefuser = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1570, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pan.setMinimumSize(new java.awt.Dimension(1200, 1200));
        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titreFenetreAffichProp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titreFenetreAffichProp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreFenetreAffichProp.setText("Vous avez reçu une proposition / demande :");
        titreFenetreAffichProp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titreFenetreAffichProp.setPreferredSize(new java.awt.Dimension(510, 40));
        pan.add(titreFenetreAffichProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 520, 50));

        nomEmetteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomEmetteur.setText("Nom émetteur : [ Nom Emetteur ]");
        nomEmetteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(nomEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 240, 20));

        nomRecepteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomRecepteur.setText("Nom récepteur : [ Nom récepteur ]");
        nomRecepteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(nomRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 250, 20));

        duree.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        duree.setText("Durée de validité : [ Durée de validité ]");
        duree.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 290, 20));

        mailEmetteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailEmetteur.setText("Mail émetteur : [ Mail émetteur ]");
        mailEmetteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(mailEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 300, 20));

        mailRecepteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailRecepteur.setText("Mail récepteur : [ Mail récepteur ]");
        mailRecepteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(mailRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 300, -1));

        coordonnees.setBackground(new java.awt.Color(210, 210, 210));
        coordonnees.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        coordonnees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coordonnees.setText("Coordonées :");
        coordonnees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coordonnees.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coordonnees.setMaximumSize(new java.awt.Dimension(120, 30));
        coordonnees.setMinimumSize(new java.awt.Dimension(120, 30));
        coordonnees.setPreferredSize(new java.awt.Dimension(120, 30));
        pan.add(coordonnees, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 520, -1));

        laProposition.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        laProposition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        laProposition.setText("La proposition :");
        laProposition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        laProposition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        laProposition.setPreferredSize(new java.awt.Dimension(110, 30));
        pan.add(laProposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 1000, -1));

        titreProp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titreProp.setText("Titre de ma proposition : [ Titre de la proposition ]");
        titreProp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(titreProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 990, -1));

        proposition.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        proposition.setText("La personne propose : ");
        pan.add(proposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 150, 180, 20));

        desire.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        desire.setText("La personne désire : ");
        pan.add(desire, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 150, -1, -1));

        boutonFaireConProp.setBackground(new java.awt.Color(204, 204, 204));
        boutonFaireConProp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonFaireConProp.setText("Faire une contre-proposition");
        boutonFaireConProp.setPreferredSize(new java.awt.Dimension(240, 40));
        boutonFaireConProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonFaireConPropActionPerformed(evt);
            }
        });
        pan.add(boutonFaireConProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        boutonAccepter.setBackground(new java.awt.Color(204, 204, 204));
        boutonAccepter.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonAccepter.setText("Accepter");
        boutonAccepter.setPreferredSize(new java.awt.Dimension(130, 40));
        boutonAccepter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAccepterActionPerformed(evt);
            }
        });
        pan.add(boutonAccepter, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        boutonRefuser.setBackground(new java.awt.Color(204, 204, 204));
        boutonRefuser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonRefuser.setText("Refuser");
        boutonRefuser.setPreferredSize(new java.awt.Dimension(130, 40));
        boutonRefuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonRefuserActionPerformed(evt);
            }
        });
        pan.add(boutonRefuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, -1, -1));

        add(pan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void boutonAccepterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAccepterActionPerformed
        XmlTools xmlTools = new XmlTools();
         
        xmlTools.accepterAccep("xml.xml");
    }//GEN-LAST:event_boutonAccepterActionPerformed

    private void boutonRefuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonRefuserActionPerformed
        XmlTools xmlTools = new XmlTools();
         
        xmlTools.refuserAccep("xml.xml");
    }//GEN-LAST:event_boutonRefuserActionPerformed

    private void boutonFaireConPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonFaireConPropActionPerformed
        // TODO mettre la fonction quand l'utilisateur veut faire une contre proposition
    }//GEN-LAST:event_boutonFaireConPropActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            iap = new InterfaceAffichProp();
            XMLParser.AfficherProp("xml.xml");
            iap.setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonAccepter;
    private javax.swing.JButton boutonFaireConProp;
    private javax.swing.JButton boutonRefuser;
    private javax.swing.JLabel coordonnees;
    private javax.swing.JLabel desire;
    public static javax.swing.JLabel duree;
    private javax.swing.JLabel laProposition;
    public static javax.swing.JLabel mailEmetteur;
    public static javax.swing.JLabel mailRecepteur;
    public static javax.swing.JLabel nomEmetteur;
    public static javax.swing.JLabel nomRecepteur;
    public static javax.swing.JPanel pan;
    private javax.swing.JLabel proposition;
    private javax.swing.JLabel titreFenetreAffichProp;
    public static javax.swing.JLabel titreProp;
    // End of variables declaration//GEN-END:variables
}
