/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.interfacegraphique;

import com.company.tools.XmlTools;
import java.awt.Color;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**
 *
 * @author qbiss
 */
public class InterfaceCreaProp extends java.awt.Frame {
    public static int estCheckDesire = 0,estCheckPropose = 0;
    /**
     * Creates new form InterfaceAut
     */
    public InterfaceCreaProp() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan = new javax.swing.JPanel();
        titreFenetreProp = new javax.swing.JLabel();
        nomEmetteur = new javax.swing.JLabel();
        texteEmetteur = new javax.swing.JTextField();
        nomRecepteur = new javax.swing.JLabel();
        texteRecepteur = new javax.swing.JTextField();
        duree = new javax.swing.JLabel();
        mailEmetteur = new javax.swing.JLabel();
        texteMailEmetteur = new javax.swing.JTextField();
        mailRecepteur = new javax.swing.JLabel();
        textMailRecepteur = new javax.swing.JTextField();
        coordonnees = new javax.swing.JLabel();
        maProposition = new javax.swing.JLabel();
        titreProp = new javax.swing.JLabel();
        texteTitreProp = new javax.swing.JTextField();
        jePropose = new javax.swing.JLabel();
        typeObjPropose = new javax.swing.JLabel();
        texteTypeObjPropose = new javax.swing.JTextField();
        descriptObjPropose = new javax.swing.JLabel();
        scrollDescObjPropose = new javax.swing.JScrollPane();
        texteDescriptObjPropose = new javax.swing.JTextPane();
        jeDesire = new javax.swing.JLabel();
        typeObjDesire = new javax.swing.JLabel();
        texteTypeObjDesire = new javax.swing.JTextField();
        descriptObjDesire = new javax.swing.JLabel();
        scrollDescObjDesire = new javax.swing.JScrollPane();
        texteDescriptObjDesire = new javax.swing.JTextPane();
        checkPasObjPropose = new javax.swing.JCheckBox();
        checkPasObjDesire = new javax.swing.JCheckBox();
        boutonValiderProp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        choixNbJour = new javax.swing.JSpinner();

        setPreferredSize(new java.awt.Dimension(535, 915));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        pan.setMinimumSize(new java.awt.Dimension(1200, 1200));
        pan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titreFenetreProp.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titreFenetreProp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titreFenetreProp.setText("Je propose un troc / J'ai une demande : ");
        titreFenetreProp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titreFenetreProp.setMaximumSize(new java.awt.Dimension(465, 40));
        titreFenetreProp.setMinimumSize(new java.awt.Dimension(465, 40));
        titreFenetreProp.setPreferredSize(new java.awt.Dimension(465, 40));
        pan.add(titreFenetreProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 500, 50));

        nomEmetteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomEmetteur.setText("Nom émetteur : *");
        nomEmetteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(nomEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 20));

        texteEmetteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteEmetteur.setNextFocusableComponent(texteRecepteur);
        pan.add(texteEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 330, 20));

        nomRecepteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        nomRecepteur.setText("Nom récepteur : *");
        nomRecepteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(nomRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 20));
        nomRecepteur.getAccessibleContext().setAccessibleName("");

        texteRecepteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteRecepteur.setNextFocusableComponent(choixNbJour);
        pan.add(texteRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 330, 20));

        duree.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        duree.setText("Durée de validité : *");
        duree.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(duree, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 20));

        mailEmetteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailEmetteur.setText("Mail émetteur :");
        mailEmetteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(mailEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 160, 20));

        texteMailEmetteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteMailEmetteur.setNextFocusableComponent(textMailRecepteur);
        pan.add(texteMailEmetteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 330, 20));

        mailRecepteur.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mailRecepteur.setText("Mail récepteur : ");
        mailRecepteur.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(mailRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 160, -1));

        textMailRecepteur.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textMailRecepteur.setNextFocusableComponent(texteTitreProp);
        pan.add(textMailRecepteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 330, -1));

        coordonnees.setBackground(new java.awt.Color(210, 210, 210));
        coordonnees.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        coordonnees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coordonnees.setText("Coordonées :");
        coordonnees.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        coordonnees.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        coordonnees.setMaximumSize(new java.awt.Dimension(110, 30));
        coordonnees.setMinimumSize(new java.awt.Dimension(110, 30));
        coordonnees.setPreferredSize(new java.awt.Dimension(110, 30));
        pan.add(coordonnees, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 480, -1));

        maProposition.setBackground(new java.awt.Color(210, 210, 210));
        maProposition.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        maProposition.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maProposition.setText("Ma proposition :");
        maProposition.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        maProposition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        maProposition.setMaximumSize(new java.awt.Dimension(110, 30));
        maProposition.setMinimumSize(new java.awt.Dimension(110, 30));
        maProposition.setPreferredSize(new java.awt.Dimension(110, 30));
        pan.add(maProposition, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 310, 480, -1));

        titreProp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        titreProp.setText("Titre de ma proposition : *");
        titreProp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(titreProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        texteTitreProp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteTitreProp.setNextFocusableComponent(texteTypeObjPropose);
        pan.add(texteTitreProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 310, -1));

        jePropose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jePropose.setText("Je propose : *");
        pan.add(jePropose, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 180, 20));

        typeObjPropose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        typeObjPropose.setText("Type de l'objet :");
        typeObjPropose.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(typeObjPropose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 170, -1));

        texteTypeObjPropose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteTypeObjPropose.setNextFocusableComponent(texteDescriptObjPropose);
        pan.add(texteTypeObjPropose, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 320, -1));

        descriptObjPropose.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        descriptObjPropose.setText("Description de l'objet : ");
        descriptObjPropose.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(descriptObjPropose, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 170, -1));

        texteDescriptObjPropose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteDescriptObjPropose.setAutoscrolls(false);
        texteDescriptObjPropose.setNextFocusableComponent(texteTypeObjDesire);
        scrollDescObjPropose.setViewportView(texteDescriptObjPropose);

        pan.add(scrollDescObjPropose, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 320, 130));

        jeDesire.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jeDesire.setText("Je désire : *");
        pan.add(jeDesire, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, -1, -1));

        typeObjDesire.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        typeObjDesire.setText("Type de l'objet :");
        typeObjDesire.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(typeObjDesire, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 170, -1));

        texteTypeObjDesire.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteTypeObjDesire.setNextFocusableComponent(texteDescriptObjDesire);
        pan.add(texteTypeObjDesire, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, 320, -1));

        descriptObjDesire.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        descriptObjDesire.setText("Description de l'objet : ");
        descriptObjDesire.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        pan.add(descriptObjDesire, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, 170, -1));

        texteDescriptObjDesire.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        texteDescriptObjDesire.setAutoscrolls(false);
        texteDescriptObjDesire.setNextFocusableComponent(boutonValiderProp);
        scrollDescObjDesire.setViewportView(texteDescriptObjDesire);

        pan.add(scrollDescObjDesire, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 690, 320, 130));

        checkPasObjPropose.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkPasObjPropose.setText("Je ne veux pas proposer d'objet");
        checkPasObjPropose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPasObjProposeActionPerformed(evt);
            }
        });
        pan.add(checkPasObjPropose, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 320, 40));

        checkPasObjDesire.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        checkPasObjDesire.setText("Je désire aucun objet");
        checkPasObjDesire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPasObjDesireActionPerformed(evt);
            }
        });
        pan.add(checkPasObjDesire, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 320, 40));

        boutonValiderProp.setBackground(new java.awt.Color(102, 204, 255));
        boutonValiderProp.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        boutonValiderProp.setText("Envoyer la proposition / demande ");
        boutonValiderProp.setMaximumSize(new java.awt.Dimension(275, 30));
        boutonValiderProp.setMinimumSize(new java.awt.Dimension(275, 30));
        boutonValiderProp.setNextFocusableComponent(texteEmetteur);
        boutonValiderProp.setPreferredSize(new java.awt.Dimension(275, 30));
        boutonValiderProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonValiderPropActionPerformed(evt);
            }
        });
        pan.add(boutonValiderProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 830, 500, 40));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Jour(s)");
        pan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, -1, 40));

        choixNbJour.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        choixNbJour.setNextFocusableComponent(texteMailEmetteur);
        choixNbJour.setValue(1);
        choixNbJour.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                choixNbJourStateChanged(evt);
            }
        });
        pan.add(choixNbJour, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 50, -1));

        add(pan, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void checkPasObjProposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPasObjProposeActionPerformed
        JCheckBox cb = (JCheckBox) evt.getSource();
        
        boolean isSel = cb.isSelected();
        
        if(isSel){
            texteDescriptObjPropose.setFocusable(false);
            texteTypeObjPropose.setFocusable(false);
            texteDescriptObjPropose.setText("");
            texteTypeObjPropose.setText("");
            texteDescriptObjPropose.setBackground(new Color(230,230,230));
            texteTypeObjPropose.setBackground(new Color(230,230,230));
            
            estCheckPropose = 1;
            
            pan.repaint();
        }
        else{
            texteDescriptObjPropose.setFocusable(true);
            texteTypeObjPropose.setFocusable(true);
            texteDescriptObjPropose.setBackground(new Color(255,255,255));
            texteTypeObjPropose.setBackground(new Color(255,255,255));
            
            estCheckPropose = 0;
            
            pan.repaint();
        }
    }//GEN-LAST:event_checkPasObjProposeActionPerformed

    private void checkPasObjDesireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPasObjDesireActionPerformed
        JCheckBox cb = (JCheckBox) evt.getSource();
        
        boolean isSel = cb.isSelected();
        
        if(isSel){
            texteDescriptObjDesire.setFocusable(false);
            texteTypeObjDesire.setFocusable(false);
            texteDescriptObjDesire.setText("");
            texteTypeObjDesire.setText("");
            texteDescriptObjDesire.setBackground(new Color(230,230,230));
            texteTypeObjDesire.setBackground(new Color(230,230,230));
            
            estCheckDesire = 1;
            
            pan.repaint();
        }
        else{
            texteDescriptObjDesire.setFocusable(true);
            texteTypeObjDesire.setFocusable(true);
            texteDescriptObjDesire.setBackground(new Color(255,255,255));
            texteTypeObjDesire.setBackground(new Color(255,255,255));
            
            estCheckDesire = 0;
            
            pan.repaint();
        }
        
    }//GEN-LAST:event_checkPasObjDesireActionPerformed

    private void boutonValiderPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonValiderPropActionPerformed
        int err = 0;
        
        if(texteEmetteur.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Le champs \"Nom émetteur\" doit être rempli!");
            err = 1;
        }
        
        if(texteRecepteur.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Le champs \"Nom récepteur\" doit être rempli!");
            err = 1;
        }
        
        
        if(texteTitreProp.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Le champs \"Titre de ma proposition\" doit être rempli!");
            err = 1;
        }
        
        
        if(estCheckPropose == 0){
            if(texteTypeObjPropose.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Le champs \"Type de l'objet\" de la section \"Je propose :\" doit être rempli!");
                err = 1;
            }
            
            if(texteDescriptObjPropose.getText().isEmpty()){
                 JOptionPane.showMessageDialog(null,"Le champs \"Description de l'objet\" de la section \"Je propose :\" doit être rempli!");
                 err = 1;
            }
        }
        
        if(estCheckDesire == 0){
            if(texteTypeObjDesire.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Le champs \"Type de l'objet\" de la section \"Je désire :\" doit être rempli!");
                err = 1;
            }
            
            if(texteDescriptObjDesire.getText().isEmpty()){
                 JOptionPane.showMessageDialog(null,"Le champs \"Description de l'objet\" de la section \"Je désire :\" doit être rempli!");
                 err = 1;
            }
        }
        
        if(err != 1){
            XmlTools xmlTools = new XmlTools();
            if(xmlTools.creerProp(texteEmetteur.getText(), texteRecepteur.getText(), (Integer)choixNbJour.getValue(),texteMailEmetteur.getText(), textMailRecepteur.getText(),texteTitreProp.getText()))
                JOptionPane.showMessageDialog(null,"Demande cree avec succes");
            else
                JOptionPane.showMessageDialog(null,"Erreur veuillez resseayer plus tard");
                
        }
    }//GEN-LAST:event_boutonValiderPropActionPerformed

    private void choixNbJourStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_choixNbJourStateChanged
        JSpinner s = (JSpinner) evt.getSource();

        int value = (Integer) s.getValue();

        if (value < 1){
            choixNbJour.setValue(1);
        }
    }//GEN-LAST:event_choixNbJourStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new InterfaceCreaProp().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonValiderProp;
    private javax.swing.JCheckBox checkPasObjDesire;
    private javax.swing.JCheckBox checkPasObjPropose;
    private javax.swing.JSpinner choixNbJour;
    private javax.swing.JLabel coordonnees;
    private javax.swing.JLabel descriptObjDesire;
    private javax.swing.JLabel descriptObjPropose;
    private javax.swing.JLabel duree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jeDesire;
    private javax.swing.JLabel jePropose;
    private javax.swing.JLabel maProposition;
    private javax.swing.JLabel mailEmetteur;
    private javax.swing.JLabel mailRecepteur;
    private javax.swing.JLabel nomEmetteur;
    private javax.swing.JLabel nomRecepteur;
    private javax.swing.JPanel pan;
    private javax.swing.JScrollPane scrollDescObjDesire;
    private javax.swing.JScrollPane scrollDescObjPropose;
    private javax.swing.JTextField textMailRecepteur;
    public static javax.swing.JTextPane texteDescriptObjDesire;
    public static javax.swing.JTextPane texteDescriptObjPropose;
    private javax.swing.JTextField texteEmetteur;
    private javax.swing.JTextField texteMailEmetteur;
    private javax.swing.JTextField texteRecepteur;
    private javax.swing.JTextField texteTitreProp;
    public static javax.swing.JTextField texteTypeObjDesire;
    public static javax.swing.JTextField texteTypeObjPropose;
    private javax.swing.JLabel titreFenetreProp;
    private javax.swing.JLabel titreProp;
    private javax.swing.JLabel typeObjDesire;
    private javax.swing.JLabel typeObjPropose;
    // End of variables declaration//GEN-END:variables
}
